[package]
authors = ["James Longino <james.longino@gmail.com>"]
edition = "2018"
name = "triangle"
version = "0.1.0"

[dependencies]
futures = "0.3"
hobby = {path = "../hobby"}
log = "0.4"
winit = "0.22"
