[package]
name = "hobby"
version = "0.1.0"
authors = ["James Longino <james.longino@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.18"
log = "0.4"
vulkano = "0.11"
vulkano-win = "0.11"
failure = "0.1"
