[package]
name = "hobby"
version = "0.1.0"
authors = ["James Longino <james.longino@gmail.com>"]

[dependencies]
winit = "0.18"
log = "0.4"
gfx-hal = {git = "https://github.com/gfx-rs/gfx"}
gfx-backend-vulkan = {git = "https://github.com/gfx-rs/gfx"}

[build-dependencies]
shaderc = "0.3"