[package]
authors = ["James Longino <james.longino@gmail.com>"]
edition = "2018"
name = "hobby"
version = "0.1.0"

[dependencies]
log = "0.4"
shaderc = "0.6"
simplelog = "0.8"
wgpu = "0.5"
winit = "0.22"
