[package]
name = "hobby"
version = "0.1.0"
authors = ["James Longino <james.longino@gmail.com>"]
edition = "2018"

[dependencies]
log = "^0.4"
winit = "0.20.0-alpha4"
raw-window-handle = "^0.3"
float-cmp = "^0.6"
gfx-hal = "^0.4"
gfx-backend-vulkan = "^0.4"

[dev-dependencies]
simplelog = "^0.7"
