[package]
name = "hobby"
version = "0.1.0"
authors = ["James Longino <james.longino@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
winit = "0.22"
ash = "0.31"

[dev-dependencies]
simplelog = "0.8"