[package]
name = "hobby"
version = "0.1.0"
authors = ["James Longino <james.longino@gmail.com>"]
edition = "2018"

[dependencies]
ash = "^0.29"
winit = "0.20.0-alpha4"
log = "^0.4"

[dev-dependencies]
simplelog = "^0.7"
