[package]
name = "colored-quad"
version = "0.1.0"
authors = ["James Longino <james.longino@gmail.com>"]
edition = "2018"

[dependencies]
hobby = { path = "../../hobby"}
simplelog = "0.5"
log = "0.4"
failure = "0.1"
nalgebra = "0.16"
nalgebra-glm = "0.2"