[package]
authors = ["James Longino <james.longino@gmail.com>"]
edition = "2018"
name = "texture"
version = "0.1.0"

[dependencies]
bytemuck = "1.3"
futures = "0.3"
hobby = {path = "../hobby"}
log = "0.4"
wgpu = "0.5"
winit = "0.22"
