[package]
name = "triangle"
version = "0.1.0"
authors = ["James Longino <james.longino@gmail.com>"]
edition = "2018"

[dependencies]
hobby = { path = "../../hobby"}
log = "0.4"
failure = "0.1"
simplelog = "0.5"
